"""pgvector extension and events audit table

Revision ID: ff44e962d75b
Revises:
Create Date: 2026-09-12

The starting state of the DocSentry data layer, written by hand rather than
autogenerated. It matches what was applied to the local container and to
Supabase before Alembic existed in this project, so both are stamped at this
revision rather than run through it.

The langchain_pg_collection and langchain_pg_embedding tables are deliberately
absent. langchain-postgres creates and owns them on first use, and a migration
that also claimed them would fight the library over the same objects.
"""

from alembic import op

revision = "ff44e962d75b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS events (
            id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

            question        TEXT         NOT NULL,
            answered        BOOLEAN      NOT NULL,
            refusal_reason  TEXT,

            citations       JSONB        NOT NULL DEFAULT '[]'::jsonb,
            flags           TEXT[]       NOT NULL DEFAULT '{}',

            -- Best retrieval score for the question. Stored because the
            -- grounding threshold is tuned against exactly this number, and
            -- tuning it blind against a test set is how it drifts out of step
            -- with production.
            top_score       DOUBLE PRECISION,

            latency_ms      INTEGER      NOT NULL
        )
        """
    )

    op.execute("CREATE INDEX IF NOT EXISTS events_created_at_idx ON events (created_at DESC)")
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS events_refused_idx
            ON events (created_at DESC)
            WHERE answered = false
        """
    )

    # The table holds the raw text of user questions, and on Supabase the public
    # schema is reachable through PostgREST with the anon key. RLS with no
    # policies denies every API role. The application connects directly over
    # Postgres as the table owner, which bypasses RLS, so nothing it does
    # changes. Harmless on a local container, where nothing sits in front of
    # the database.
    op.execute("ALTER TABLE events ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # The extension is left alone. Dropping it would take the vector columns
    # langchain-postgres owns with it, which is a far larger blast radius than
    # undoing this revision should have.
    op.execute("DROP TABLE IF EXISTS events")
